family: hibernate
identifier: hibernate-orm-reference
name: Hibernate ORM User Guide
baseUri: https://docs.jboss.org/hibernate/orm/6.1/userguide/html_single/
index: Hibernate_User_Guide.html
titleSelector: h1
