family: spring
identifier: spring-security-reference
name: Spring Security Reference Documentation
baseUri: https://docs.spring.io/spring-security/reference/
index: index.html
titleSelector: h1
dontIndex: index\.html
dontCrawl: ^\d+\.\d+(?:\.\d+)?(?:-SNAPSHOT|-RC\d+|CURRENT)?/
